# Generated by Django 4.0.4 on 2022-08-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.TextField(default='https://www.noietch.cn/resource/logo.png', null=True),
        ),
    ]
