# Generated by Django 3.2.8 on 2022-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='personal_group',
            field=models.IntegerField(default=0),
        ),
    ]
