# Generated by Django 3.2.8 on 2022-08-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cur_group',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
