# Generated by Django 3.2.8 on 2022-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.IntegerField()),
                ('avatar', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupsRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
