# Generated by Django 3.2.5 on 2022-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='groups',
        #     name='avatar',
        #     field=models.TextField(null=True),
        # ),
    ]
