# Generated by Django 4.0.4 on 2022-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='groups',
        #     name='avatar',
        #     field=models.TextField(null=True),
        # ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
