# Generated by Django 3.2.5 on 2022-08-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='avatar',
            field=models.TextField(default='https://dn-st.teambition.net/teambition/images/logo1.a6464e9c.jpg'),
        ),
    ]
