# Generated by Django 4.0.4 on 2022-08-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_avatar_alter_groups_name'),
    ]

    operations = [
        
    ]
