# Generated by Django 3.2.5 on 2022-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_avatar'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='groups',
        #     name='avatar',
        #     field=models.TextField(null=True),
        # ),
        # migrations.AlterField(
        #     model_name='groups',
        #     name='name',
        #     field=models.CharField(max_length=50),
        # ),
    ]
