# Generated by Django 4.0.4 on 2022-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_avatar'),
    ]

    operations = [
        
    ]
