# Generated by Django 3.2.5 on 2022-08-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='document',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='project',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='prototype',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='uml',
        #     name='is_deleted',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='document',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prototype',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uml',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
