# Generated by Django 3.2.8 on 2022-08-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220808_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='img_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
