# Generated by Django 3.2.8 on 2022-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_prototype_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
