# Generated by Django 3.2.8 on 2022-08-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_document_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='label',
            field=models.CharField(default='项目计划', max_length=100, null=True),
        ),
    ]
