# Generated by Django 3.2.5 on 2022-08-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220803_1625'),
    ]

    operations = [
    ]
