# Generated by Django 3.2.8 on 2022-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_prototype_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='encryption',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
