# Generated by Django 3.2.8 on 2022-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cow',
            field=models.IntegerField(default=0),
        ),
    ]
