# Generated by Django 4.0.4 on 2022-08-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_document_avatar_project_avatar_prototype_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototype',
            name='route',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
