# Generated by Django 3.2.8 on 2022-08-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge_0003_auto_20220803_1625_0003_document_label'),
        ('projects', '0006_document_cow'),
    ]

    operations = [
    ]
