# Generated by Django 3.2.8 on 2022-08-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20220810_0237')
    ]

    operations = [
        migrations.AddField(
            model_name='uml',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='project_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
