# Generated by Django 4.0.4 on 2022-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_document_avatar_project_avatar_prototype_avatar_and_more'),
    ]

    operations = [
        
    ]
