# Generated by Django 3.2.8 on 2022-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220810_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='online_users',
            field=models.IntegerField(default=0),
        ),
    ]
