# Generated by Django 3.2.8 on 2022-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_document_online_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='online_users',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
